name: Main CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build -f ./api/Dockerfile.dev -t pholawat5/jwt-api ./api
    
    - name: Test the Docker image
      run: docker run pholawat5/jwt-api npm run test
